### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by dingledow** [Pisys/elm-tapbox#3]
I try to run `elm-package install Pisys/elm-mousetouch` but it can't find it.  What's the best way to install this?

**Comment by pisys** [comment]
Sorry, elm-mousetouch is not in the Elm package repository because it's still in an experimental state. 
You can install it by cloning this repository

```
git clone git@github.com:Pisys/elm-mousetouch.git
```

and then add its source path, eg. `path/to/elm-mousetouch/src`, to the source-directories in your project's `elm-package.json`.

**Comment by dingledow** [comment]
Thanks for the direction! 😄 

```
"source-directories": [
        ".",
        "./elm-mousetouch/src/"
    ],
```

I have `elm-mousetouch` in my root folder, but still getting this error:

```
Message:
    I cannot find find module 'Native.MouseTouch'.

Module 'MouseTouch' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.son
```

Any thoughts?

**Comment by pisys** [comment]
Sorry, forgot to mention that you need to add `"native-modules" : true` to your `elm-package.json`. The compiler will look for native modules in your project then.

**Comment by dingledow** [comment]
Thanks, that got it working!
